addons:
  postgresql: "9.3"
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y --force-yes
before_script:
  - rethinkdb --io-threads 64 --cache-size auto --bind all -c 2 &
  - sleep 10
  - psql -c 'create database ger_test;' -U postgres
language: node_js
node_js:
  - "0.12"
after_script:
  - killall rethinkdb